###
POST {{content_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203001"
}

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 130,
  "originalPrice":129,
  "qq": "233",
  "wechat": "412",
  "phone": "413",
  "validDays": 3650,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "3fd",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "efes",
  "grade": "204001",
  "description": "fesf頥"
}

### 根据课程id查询课程信息
GET {{content_host}}/content/course/40
Content-Type: application/json

### 修改课程
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id": 40,
  "tags": "Spring项目的快速构建",
  "mt": "1-3",
  "st": "1-3-2",
  "grade": "200003",
  "teachmode": "201001",
  "description": "课程系统性地深度探讨 Spring Boot 核心特性，引导小伙伴对 Java 规范的重视，启发对技术原理性的思考，掌握排查问题的技能，以及学习阅读源码的方法和技巧，全面提升研发能力，进军架构师队伍。",
  "pic": "https://cdn.educba.com/academy/wp-content/uploads/2018/08/Spring-BOOT-Interview-questions.jpg",
  "charge": "201001",
  "price": 0.01
}

### 查询某个课程的课程计划

GET {{content_host}}/content/teachplan/75/tree-nodes

### 新增课程计划--章,当grade为1时parentid为0
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 0,
  "grade" : 1,
  "pname" : "2新大章牛逼名称 [点击修改]"
}

### 新增课程计划--节
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 247,
  "grade" : 2,
  "pname" : "新小节牛逼名称 [点击修改]"
}

### 修改课程计划,需要从数据库找到修改的课程计划id
PUT {{content_host}}/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 22,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "2",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 237,
  "pname" : "第1节修改名称",
  "startTime" : null,
  "status" : null,
  "teachPlanId" : 240
}

### 根据课程id查询教师信息
GET {{content_host}}/content/courseTeacher/list/75

### 新增教师
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "courseId": 75,
  "teacherName": "王老师",
  "position": "教师职位",
  "introduction": "教师简介"
}

### 修改课程教师
PUT {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 21,
  "courseId": 75,
  "teacherName": "王老师王老师",
  "position": "教师职位王老师",
  "introduction": "教师简介王老师",
  "photograph": null,
  "createDate": null
}

### 通过教师id和课程id删除课程计划信息
DELETE {{content_host}}/content/courseTeacher/course/75/26

### 通过课程计划id删除课程
DELETE {{content_host}}/content/teachplan/12

### 课程计划上移
POST {{content_host}}/content/teachplan/moveup/12

### 课程计划下移
POST {{content_host}}/content/teachplan/movedown/12

### 删除课程
DELETE {{content_host}}/content/course/87

